
services:
  postgres:
    image: postgres:18-alpine
    container_name: wishlister-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: wishlister
      POSTGRES_PASSWORD: wishlister
      POSTGRES_DB: wishlister
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wishlister"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - wishlister-network

  valkey:
    image: valkey/valkey:9-alpine 
    container_name: wishlister-valkey
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - valkey-data:/var/lib/valkey
    command: ["valkey-server", "--requirepass", "wishlister", "--save", "20", "1", "--loglevel", "warning"]
    environment:
      - VALKEY_PASSWORD=wishlister
    restart: unless-stopped
    networks:
      - wishlister-network

  core:
    build:
      context: ./services/wishlist/
      dockerfile: ./deployments/Dockerfile
    container_name: wishlister-core
    restart: unless-stopped
    env_file:
      - ./services/wishlist/deployments/.compose.env
    ports:
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 3s
      start_interval: 5s
    networks:
      - wishlister-network

  tg-bot:
    build:
      context: ./services/telegram-bot/
      dockerfile: ./deployments/Dockerfile
    container_name: wishlister-tg-bot
    restart: unless-stopped
    env_file: 
      - ./services/telegram-bot/deployments/.compose.env
    depends_on:
      core:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 3s
      start_interval: 5s
    networks:
      - wishlister-network

volumes:
  postgres-data:
  valkey-data:

networks:
  wishlister-network:
    driver: bridge